# Generated by Django 3.0 on 2022-04-07 20:16

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titre', unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='CREER Le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='MIS A JOUR le')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='articles.Categorie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat', models.CharField(max_length=25)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_reduction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix avec réduction')),
                ('composition', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('actif', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='plat', unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='CREER Le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='MIS A JOUR le')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='articles.Categorie')),
            ],
        ),
    ]
