# Generated by Django 3.0 on 2022-04-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
