# Generated by Django 3.0 on 2022-04-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20220408_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='prix_reduction',
        ),
    ]
