# Generated by Django 3.0 on 2022-04-08 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité')),
                ('commande', models.BooleanField(default=False, verbose_name='Commandé')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True, verbose_name='Date de début')),
                ('date_commande', models.DateTimeField(verbose_name='Date de commande')),
                ('commande', models.BooleanField(default=False, verbose_name='Commandé')),
                ('commande_livre', models.BooleanField(default=False, verbose_name='Livré')),
                ('commande_recu', models.BooleanField(default=False, verbose_name='Réceptionné')),
                ('confirmer_livraison', models.BooleanField(default=False, verbose_name='Confirmation de livraison')),
                ('demande_remboursement', models.BooleanField(default=False, verbose_name='Remboursement demandé')),
                ('remboursement_accorde', models.BooleanField(default=False, verbose_name='Remboursement accordé')),
                ('articles', models.ManyToManyField(related_name='articles', to='commande.Panier', verbose_name='Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
