# Generated by Django 3.0 on 2022-04-08 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commande', '0003_auto_20220408_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('montant_payement', models.FloatField(verbose_name='Montant')),
                ('horodatage', models.DateTimeField(auto_now_add=True, verbose_name='horodatage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse1', models.CharField(max_length=100, verbose_name='Adresse 1')),
                ('adresse2', models.CharField(max_length=100, verbose_name='Adresse 2')),
                ('ville', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=50, verbose_name='Numéro de téléphone')),
                ('code_postal', models.CharField(max_length=100, verbose_name='Code postal')),
                ('type_adresse', models.CharField(choices=[('L', 'livraison'), ('F', 'facturation')], max_length=1, verbose_name="type d'adresse")),
                ('adresse_par_defaut', models.BooleanField(default=False, verbose_name='Adresse par défaut')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse_facturation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adresse_facturation', to='commande.Adresse', verbose_name='Adresse de facturation'),
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adresse_livraison', to='commande.Adresse', verbose_name='Adresse de livraison'),
        ),
        migrations.AddField(
            model_name='commande',
            name='payement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commande.Payement', verbose_name='Payement'),
        ),
    ]
